# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloJuego', models.CharField(max_length=30)),
                ('generoJuego', models.CharField(max_length=30)),
                ('idiomaJuego', models.CharField(max_length=20)),
                ('numeroJugador', models.CharField(max_length=20)),
                ('fechaLanzamiento', models.DateTimeField()),
                ('companiaJuego', models.CharField(choices=[('Nintendo', 'Nintendo'), ('Sony', 'Sony'), ('Microsoft', 'Microsoft'), ('Ubisoft', 'Ubisoft'), ('Bethesda', 'Bethesda'), ('SquareEnix', 'SquareEnix'), ('SEGA', 'SEGA')], default='MICROSOFT', max_length=20)),
                ('plataformaJuego', models.CharField(choices=[('Ps4', 'Ps4'), ('Xbox One', 'Xbox One'), ('Nintendo Switch', 'Nintendo Switch'), ('Pc', 'Pc')], default='PS4', max_length=20)),
                ('editorJuego', models.CharField(choices=[('Bethesda', 'Bethesda'), ('Nintendo', 'Nintendo'), ('SEGA', 'SEGA'), ('Ubisoft', 'Ubisoft'), ('Sony', 'Sony'), ('SquareEnix', 'SquareEnix'), ('Microsoft', 'Microsoft')], default='BETHESDA', max_length=20)),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
